openapi: 3.0.0
info:
  title: Purse application
  version: 1.0.1
  description: This application is the first numeric bank at our country
servers:
  - url: http://localhost:8080
tags:
  - name: Client
  - name: Account
  - name: Bank
  - name: Transaction
  - name: Interest
  - name: Functionnality
  - name: ApplyInterest
paths:
  /client/all:
    get:
      tags:
        - Client
      summary: get all Client
      operationId: getClients
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListBody'
                  - properties:
                      body:
                        items:
                          $ref: '#/components/schemas/Client'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /client/{id}:
    get:
      tags:
        - Client
      summary: get one client by id
      operationId: getClientById
      parameters:
        - in: path
          name: id 
          required: true
          description: get by id 
          schema: 
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Client'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /client/delete:
    delete:
      tags:
        - Client
      summary: delete one client
      operationId: deleteClient
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Client"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Client'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /client/new: 
    post:
      tags:
        - Client
      summary: create new client
      operationId: createClient
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Client"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Client'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /client/update:
    put:  
      tags:
        - Client
      summary: crupdate client
      operationId: crupdateClient
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Client"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Client'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"


#-------------------Account------------------
  /account/all:
    get:
      tags:
        - Account
      summary: get all Account
      operationId: getAccounts
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListBody'
                  - properties:
                      body:
                        items:
                          $ref: '#/components/schemas/Account'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /account/{idClient}:
    get:
      tags:
        - Account
      summary: get accounts by client's id
      operationId: getAccountByClientId
      parameters:
        - in: path
          name: idClient 
          required: true
          description: get by client's id 
          schema: 
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListBody'
                  - properties:
                      body:
                        items:
                          $ref: '#/components/schemas/Account'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /account/accountInterest:
    get:
      tags:
        - Account
      summary: get interest by account's id
      operationId: getAccountInterestById
      parameters:
        - in: query
          name: id
          required: true
          description: get account's interest 
          schema: 
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/AccountInterest'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /account/new: 
    post:
      tags:
        - Account
      summary: create new account
      operationId: createAccount
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Account"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Account'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /account/creditAuthorization:
    put:
      tags:
        - "Account"
      summary: enable an account to make a credit 
      operationId: creditAuthorization 
      parameters:
        - name: id
          in: query
          required: true
          schema: 
            type: string
        - name: newCount
          in: query
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        items:
                          type: string
                        example: success
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

#-----------------Bank-----------------
  /bank/all:
    get:
      tags:
        - Bank
      summary: get all bank
      operationId: getbanks
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListBody'
                  - properties:
                      body:
                        items:
                          $ref: '#/components/schemas/Bank'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /bank/new: 
    post:
      tags:
        - Bank
      summary: create new bank
      operationId: createbank
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Bank"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Bank'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

#-----------Transaction----------------------
  /transaction/all:
    get:
      tags:
        - Transaction
      summary: get all transaction
      operationId: gettransactions
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListBody'
                  - properties:
                      body:
                        items:
                          $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /transaction/{byAccountId}:
    get:
      tags:
        - Transaction
      summary: get one transaction by account's id
      operationId: gettransactionByAccountId
      parameters:
        - in: path
          name: byAccountId
          required: true
          description: get by account's id 
          schema: 
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /transaction/{byClientId}:
    get:
      tags:
        - Transaction
      summary: get one transaction by client's id
      operationId: gettransactionByClientId
      parameters:
        - in: path
          name: byClientId
          required: true
          description: get by account's id 
          schema: 
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ListBody'
                  - properties:
                      body:
                        items:
                          $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /transaction/categorize:
    post:
      tags:
        - Transaction
      summary: categorize one transaction
      operationId: categorizeOneTransaction
      parameters:
        - in: query
          name: type 
          required: true
          schema: 
            type: string
        - in: query
          name: name  
          required: true
          schema: 
            type: string
        - in: query
          name: idTransaction 
          required: true
          schema: 
            type: integer
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        items:
                          type: string
                        example: "Transaction coategorized successfuly"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /transaction/categorizeSeveral:
    post:
      tags:
        - Transaction
      summary: categorize several transaction
      operationId: categorizeSeveralTransaction
      parameters:
        - in: query
          name: type 
          required: true
          schema: 
            type: string
        - in: query
          name: name  
          required: true
          schema: 
            type: string
        - in: query
          name: idTransactions 
          required: true
          schema: 
            type: array
            properties:
              idTransaction:
                type: integer
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        items:
                          type: string
                        example: "Transactions coategorized successfuly"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /transaction/new: 
    post:
      tags:
        - Transaction
      summary: create new transaction
      operationId: createtransaction
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /transaction/byAccountId:
    get: 
      tags:
        - "Transaction"
      summary: get one transaction by account id
      operationId: gettransactionByAccountId
      parameters:
        - in: query
          name: id 
          required: true
          description: get by account id 
          schema: 
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Transaction'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /transaction/sum:
    get:
      tags:
        - Transaction
      summary: get sum of expense and income on defined date  
      operationId: ExpenseIncomeSum
      parameters:
        - name: accountId  
          in: query
          required: true
          schema: 
            type: string
        - name: startDate 
          in: query
          required: true
          schema: 
            type: string
            format: date 
        - name: endDate 
          in: query
          required: true
          schema: 
            type: string
            format: date 
      responses:
        '200': 
          description: success
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: "#/components/schemas/SumIncomeExpense"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  

#---------------Interest----------------
  /interest/getOne:
    get:
      tags:
        - Interest
      summary: get one interest by id
      operationId: getinterestById
      parameters:
        - in: query
          name: id 
          required: true
          description: get by id 
          schema: 
            type: string
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Interest'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /interest/new: 
    post:
      tags:
        - Interest
      summary: create new interest
      operationId: createinterest
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/Interest"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/Interest'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

#----------funtionnality-----------

  /makeSupply:
    post:
      tags:
        - "Functionnality"
      summary: make supply on account
      operationId: makeSupply 
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/SupplyBody"
      responses:
        '200':
          description: success 
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        items:
                          type: number
                        example: 1
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /transfer:
    post:   
      tags:
        - "Functionnality"
      summary: make transfer between two account
      operationId: transfer
      parameters:
        - name: amount
          in: query
          description: amount to transfer
          required: true
          schema: 
            type: number
        - name: idAccountDebited
          in: query
          required: true
          schema: 
            type: string
        - name: idAccountCredited
          in: query
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: "#/components/schemas/TransferHistory"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
          
  /multiTransfer:
    post: 
      tags:
        - "Functionnality"
      summary: make multiple transfer between two account
      operationId: multiTransfer
      parameters:
        - name: amount
          in: query
          description: amount to transfer
          required: true
          schema: 
            type: number
        - name: idAccountDebited
          in: query
          required: true
          schema: 
            type: string
        - name: idAccountCreditedList
          in: query
          required: true
          schema: 
            type: array
            items:
              type: string
      responses:
        '200':
          description: success
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        type: array
                        items:
                          $ref: "#/components/schemas/TransferHistory"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /scheduledTransfer:
    post:   
      tags:
        - "Functionnality"
      summary: make scheduled transfer between two account
      operationId: scheduledTransfer
      parameters:
        - name: amount
          in: query
          description: amount to transfer
          required: true
          schema: 
            type: number
        - name: idAccountDebited
          in: query
          required: true
          schema: 
            type: string
        - name: idAccountCredited
          in: query
          required: true
          schema: 
            type: string
        - name: newEffectiveDate
          in: query
          required: true
          schema: 
            type: string
            format: date
      responses:
        '200':
          description: success
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: "#/components/schemas/TransferHistory"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
          
  /canceledTransaction:
    post:
      tags:
        - "Functionnality"
      summary: canceled a transaction 
      operationId: canceledTransaction 
      parameters:
        - name: id
          in: query
          required: true
          schema: 
            type: string
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        items:
                          type: string
                        example: "Canceled successfuly"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /getStatement:
    get:
      tags:
        - "Functionnality"
      summary: get account statement 
      operationId: accountStatement 
      parameters:
        - name: idAccount 
          in: query
          required: true
          schema: 
            type: string
      responses:
        '200': 
          description: success
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: "#/components/schemas/AccountStatement"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
  /categories/sum:
    get:
      tags:
        - "Functionnality"
      summary: get sum off categories due on defined date  
      operationId: categorieSum
      parameters:
        - name: accountId  
          in: query
          required: true
          schema: 
            type: string
        - name: startDate 
          in: query
          required: true
          schema: 
            type: string
            format: date 
        - name: endDate 
          in: query
          required: true
          schema: 
            type: string
            format: date 
      responses:
        '200': 
          description: success
          content:
            application/json:
              schema: 
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: "#/components/schemas/CategorieSum"
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"

  /applyInterest/new:
    post: 
      tags:
        - "ApplyInterest"
      summary: add a new apply interest 
      operationId: newApplyInterest
      requestBody:
        content:
          application/json:
            schema: 
              $ref: "#/components/schemas/ApplyInterest"
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/ApplyInterest'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
 
  /applyInterest/getOne:
    get: 
      tags:
        - "ApplyInterest"
      summary: get one apply interest
      operationId: getOneaApplyInterest
      parameters:
        - name: id 
          in: query
          required: true
          schema: 
            type: number
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/ResponseBody'
                  - properties:
                      body:
                        $ref: '#/components/schemas/ApplyInterest'
        '400':
          description: Bad request 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/BadRequest"
        '403':
          description: Forbidden
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Forbidden"
        '404':
          description: NotFound
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/NotFound"
        '500':
          description: Server error
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ServerError"
 

components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: string
        firstname:
          type: string
        lastname:
          type: string
        birthdate:
          type: string
          format: date
        monthlyPay:
          type: integer
    Account:
      type: object
      properties:
        id:
          type: string
        balance:
          type: integer
        creditAuthorization:
          type: boolean
        idClient:
          type: string
        idBank:
          type: integer
    AccountStatement:
      type: object
      properties:
        effectiveDate:
          type: string
          format: date
        reference:
          type: string
        motif:
          type: string
        creditMGA: 
          type: number
          format: double
        debitMGA:
          type: number
          format: double
        balance:
          type: number
          format: double
    CategorieSum:
      type: object
      properties:
        categoryName:
          type: string
        categoryId:
          type: integer
        totalAmount:
          type: number
          format: double
    SumIncomeExpense:
      type: object
      properties:
        categoryName:
          type: string
        categoryId:
          type: integer
        totalAmount:
          type: number
          format: double
        operationType: 
          type: string
    AccountInterest:
      type: object
      properties:
        idAccount: 
          type: string
        actualDue:
          type: number
          format: double
        firstDue:
          type: number
          format: double
        counts:
          type: number
          format: double
    Interest:
      type: object
      properties:
        id:
          type: integer
        count:
          type: integer
        dayGone:
          type: integer
    Bank:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
          enum:
            - Incoming
            - Outgoing
            - Loan
        name:
          type: string
          enum:
            - Food_and_Drinks
            - Online_Shopping
            - Housing
            - Transportation
            - Vehicle
            - Leisure
            - Multimedia_and_Computers
            - Financial_Expenses
            - Investments
            - Income
            - Other
            - Unknown
    Transaction:
      type: object
      properties:
        id: 
          type: string
        type:
          type: string
        description:
          type: string
        registrationDate:
          type: string
          format: date
        effectiveDate:
          type: string
          format: date
        amount:
          type: integer
        status:
          type: boolean
        reference:
          type: string
        idAccount:
          type: string
        idCategory:
          type: integer
    TransferHistory:
      type: object
      properties:
        id:
          type: integer
        idAccountDebited:
          type: string
        idAccountCredited:
          type: string
    SupplyBody:
      type: object
      properties:
        action:
          type: string
          enum:
            - Outgoing
            - Incoming
            - Loan
        supplyAmont:
          type: number
          format: double
        idAccount:
          type: string
        actionName:
          type: string
          enum:
            - Food_and_Drinks
            - Online_Shopping
            - Housing
            - Transportation
            - Vehicle
            - Leisure
            - Multimedia_and_Computers
            - Financial_Expenses
            - Investments
            - Income
            - Other
            - Unknown
        label:
          type: string
    ApplyInterest:
      type: object
      properties:
        id: 
          type: number
        idAccount:
          type: string 
        idInterest:
          type: number
        startDate:
          type: string
          format: date
        firstDue:
          type: number
          format: double
        actualDue:
          type: number
          format: double
    Exception:
      type: object
      properties:
        status:
          type: object
          properties:
            status_code:
              type: string
              example: 200
            message:
              type: string
              example: OK
        body: 
          type: object

    ResponseSuccessfully:
      allOf:
        - $ref: '#/components/schemas/Exception'
    
    BadRequest:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        status:
          status_code: 400
          message: BAD REQUEST 
        body: { }

    
    Forbidden:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        status:
          status_code: 403
          message: FORBIDDEN 
        body: { }

    NotFound:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        status:
          status_code: 404
          message: NOT FOUND 
        body: { }

    ServerError:
      allOf:
        - $ref: '#/components/schemas/Exception'
      example:
        status: 
          status_code: 500
          message: SERVOR ERROR 
        body: { }

    ListBody: 
      allOf:
        - $ref: '#/components/schemas/Exception'
        - properties:
            body:
              type: array

    ResponseBody:
      allOf:
        - $ref: '#/components/schemas/Exception'
        - properties:
            body:
              type: object

  responses:
    ListSuccess:
      description: Liste d'éléments
      content:
        application/json:
          schema:
            type: object
            properties:
              body:
                type: array
    
    ResponseBodySuccess:
      description: un composant 
      content:
        application/json:
          schema: 
            type: object

